<a href="https://colab.research.google.com/github/Lyyyy16/Pr-ctica-1-262519/blob/main/30_09_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Práctica extracción y exploración de datos desde JSON y PDF

In [47]:
import pandas as pd
import numpy as np

In [48]:
df_json = pd.read_json("/datos_estudiantes.json", encoding='latin1')

df_json.head()

,ID,Nombre,Edad,Semestre,Carrera,Modalidad,ProgramaciÃ³n,MatemÃ¡ticas,Ciencia de Datos,Asistencia (%),Tareas entregadas,Horas estudio semanal,Horas sueÃ±o,Uso plataforma semanal,Trabajo en equipo,Dispositivo principal
0,101,Ana LÃ³pez,19,2,IngenierÃ­a en Software,Presencial,88,82,91,95,10,8,7.5,6,SÃ­,Laptop
1,102,Carlos Rivera,21,4,Ciencia de Datos,Presencial,76,85,89,87,9,6,6.5,5,SÃ­,Laptop
2,103,SofÃ­a MartÃ­nez,20,3,IngenierÃ­a en Software,HÃ­brida,94,90,93,98,10,12,8.0,8,SÃ­,Laptop
3,104,Daniel Torres,22,6,Sistemas Computacionales,Presencial,68,74,72,80,8,4,6.0,3,No,Computadora
4,105,Mariana GarcÃ­a,19,2,Ciencia de Datos,HÃ­brida,91,88,95,96,10,10,7.5,7,SÃ­,Laptop

In [49]:
#Dimensión del dataset
df_json.shape

(12, 16)

In [50]:
#Información general
df_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      12 non-null     int64
 1   Nombre                  12 non-null     object
 2   Edad                    12 non-null     int64
 3   Semestre                12 non-null     int64
 4   Carrera                 12 non-null     object
 5   Modalidad               12 non-null     object
 6   ProgramaciÃ³n           12 non-null     int64
 7   MatemÃ¡ticas            12 non-null     int64
 8   Ciencia de Datos        12 non-null     int64
 9   Asistencia (%)          12 non-null     int64
 10  Tareas entregadas       12 non-null     int64
 11  Horas estudio semanal   12 non-null     int64
 12  Horas sueÃ±o            12 non-null     float64
 13  Uso plataforma semanal  12 non-null     int64
 14  Trabajo en equipo       12 non-null     object
 15  Dispositivo principal   12 non-null     object
dtypes: float64(1), int64(10), object(5)
memory usage: 1.6+ KB

In [51]:
df_json.describe()

,ID,Edad,Semestre,ProgramaciÃ³n,MatemÃ¡ticas,Ciencia de Datos,Asistencia (%),Tareas entregadas,Horas estudio semanal,Horas sueÃ±o,Uso plataforma semanal
count,12.000000,12.00000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,106.500000,20.75000,4.250000,82.333333,82.750000,85.583333,89.416667,9.000000,8.083333,6.916667,5.916667
std,3.605551,1.76455,2.179449,10.192094,7.898504,9.385272,8.095547,1.206045,3.315483,0.821123,1.975225
min,101.000000,18.00000,1.000000,65.000000,69.000000,70.000000,76.000000,7.000000,3.000000,5.500000,3.000000
25%,103.750000,19.75000,2.750000,75.000000,77.750000,76.500000,83.750000,8.000000,5.750000,6.375000,4.750000
50%,106.500000,20.50000,4.000000,85.000000,83.500000,89.500000,92.000000,9.500000,8.000000,7.000000,6.000000
75%,109.250000,22.00000,6.000000,90.250000,88.500000,92.250000,95.250000,10.000000,10.250000,7.500000,7.250000
max,112.000000,24.00000,8.000000,95.000000,94.000000,96.000000,100.000000,10.000000,14.000000,8.000000,9.000000

In [52]:
df_json.isnull().sum()

ID                        0
Nombre                    0
Edad                      0
Semestre                  0
Carrera                   0
Modalidad                 0
ProgramaciÃ³n             0
MatemÃ¡ticas              0
Ciencia de Datos          0
Asistencia (%)            0
Tareas entregadas         0
Horas estudio semanal     0
Horas sueÃ±o              0
Uso plataforma semanal    0
Trabajo en equipo         0
Dispositivo principal     0
dtype: int64

In [53]:
#Distribución por carrera
df_json["Carrera"].value_counts()

Carrera
Ciencia de Datos            5
IngenierÃ­a en Software     4
Sistemas Computacionales    3
Name: count, dtype: int64

In [54]:
df_json['Modalidad'].value_counts()

Modalidad
Presencial    8
HÃ­brida      4
Name: count, dtype: int64

In [55]:
df_json["Dispositivo principal"].value_counts()

Dispositivo principal
Laptop         9
Computadora    2
Tablet         1
Name: count, dtype: int64

In [59]:
# Importación de PDF
# 1. Instalar e importar libreria
!pip install pdfplumber

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.13/dist-packages (0.11.10)
Requirement already satisfied: pdfminer.six==20260107 in /usr/local/lib/python3.13/dist-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in /usr/local/lib/python3.13/dist-packages (from pdfplumber) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in /usr/local/lib/python3.13/dist-packages (from pdfplumber) (5.14.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (3.4.9)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)

In [60]:
ipip,install

NameError: name 'ipip' is not defined

In [ ]:
#Importar libreria para abrir y leer archivos PDF.
import pdflumber
import pandas as pd
#Modulo re, permite trabajar con expresiones regulares
#para buscar patrones dentro de texto

In [ ]:
#Crear una cadena de texto vacía
texto = ""

with pdflumbre.open("/content/datos_estudiantes.pdf") as pdf:
  texto += pagina.extract_text() + "\n"

print(texto)

In [ ]:
import re

patron_demografico = re.compile(
    #^ indica que la búsqueda debe de comenzar al inicio de una línea
    #(\d{3}) busca exactamente 3 dígitos: corresponde al ID
    #\s+ representa uno o más espacios
    #(.+?) captura el nombre del estudiante
    #(\d+) captura la edad
    #(\d+) captura el semestre
  r"^(\d{3})\s+(.+?)\s+(\d+)\s+(\d+)"

  #Busca una de las tres carreras posibles
  r"(Ingeniería en Software|Ciencia de Datos|Sistemas Computacionales)"

  #Busca una de las dos modalidades posibles
  r"(Presencial|Híbrida)$",

  re.MULTILINE
)

In [ ]:
#Busca dentro de "texto" todas las líneas que cumplen con el patrón que acabamos de definir
datos_demograficos = patron_demografico.findall(texto)

datos_demograficos

In [ ]:
#Convertir los datos demograficos en un DataFrame de pandas
df_demograficos = pd.DataFrame(
  datos_demograficos,
  columns=["ID", "Nombre", "Edad", "Semestre", "Carrera", "Modalidad"])

df_demograficos.head()

#Tarea
Extraer las dos columnas restantes:
calificaciones y hábitos