<a href="https://colab.research.google.com/github/Lyyyy16/Pr-ctica-1-262519/blob/main/Tarea_30_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Práctica extracción y exploración de datos desde JSON y PDF

In [74]:
import pandas as pd
import numpy as np

In [75]:
df_json = pd.read_json("/content/datos_estudiantes.json")

df_json.head()

,ID,Nombre,Edad,Semestre,Carrera,Modalidad,Programación,Matemáticas,Ciencia de Datos,Asistencia (%),Tareas entregadas,Horas estudio semanal,Horas sueño,Uso plataforma semanal,Trabajo en equipo,Dispositivo principal
0,101,Ana López,19,2,Ingeniería en Software,Presencial,88,82,91,95,10,8,7.5,6,Sí,Laptop
1,102,Carlos Rivera,21,4,Ciencia de Datos,Presencial,76,85,89,87,9,6,6.5,5,Sí,Laptop
2,103,Sofía Martínez,20,3,Ingeniería en Software,Híbrida,94,90,93,98,10,12,8.0,8,Sí,Laptop
3,104,Daniel Torres,22,6,Sistemas Computacionales,Presencial,68,74,72,80,8,4,6.0,3,No,Computadora
4,105,Mariana García,19,2,Ciencia de Datos,Híbrida,91,88,95,96,10,10,7.5,7,Sí,Laptop

In [76]:
#Dimensión del dataset
df_json.shape

(12, 16)

In [77]:
#Informacióm general
df_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      12 non-null     int64
 1   Nombre                  12 non-null     object
 2   Edad                    12 non-null     int64
 3   Semestre                12 non-null     int64
 4   Carrera                 12 non-null     object
 5   Modalidad               12 non-null     object
 6   Programación            12 non-null     int64
 7   Matemáticas             12 non-null     int64
 8   Ciencia de Datos        12 non-null     int64
 9   Asistencia (%)          12 non-null     int64
 10  Tareas entregadas       12 non-null     int64
 11  Horas estudio semanal   12 non-null     int64
 12  Horas sueño             12 non-null     float64
 13  Uso plataforma semanal  12 non-null     int64
 14  Trabajo en equipo       12 non-null     object
 15  Dispositivo principal   12 non-null     object
dtypes: float64(1), int64(10), object(5)
memory usage: 1.6+ KB

In [78]:
df_json.describe()

,ID,Edad,Semestre,Programación,Matemáticas,Ciencia de Datos,Asistencia (%),Tareas entregadas,Horas estudio semanal,Horas sueño,Uso plataforma semanal
count,12.000000,12.00000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,106.500000,20.75000,4.250000,82.333333,82.750000,85.583333,89.416667,9.000000,8.083333,6.916667,5.916667
std,3.605551,1.76455,2.179449,10.192094,7.898504,9.385272,8.095547,1.206045,3.315483,0.821123,1.975225
min,101.000000,18.00000,1.000000,65.000000,69.000000,70.000000,76.000000,7.000000,3.000000,5.500000,3.000000
25%,103.750000,19.75000,2.750000,75.000000,77.750000,76.500000,83.750000,8.000000,5.750000,6.375000,4.750000
50%,106.500000,20.50000,4.000000,85.000000,83.500000,89.500000,92.000000,9.500000,8.000000,7.000000,6.000000
75%,109.250000,22.00000,6.000000,90.250000,88.500000,92.250000,95.250000,10.000000,10.250000,7.500000,7.250000
max,112.000000,24.00000,8.000000,95.000000,94.000000,96.000000,100.000000,10.000000,14.000000,8.000000,9.000000

In [79]:
df_json.isnull().sum()

ID                        0
Nombre                    0
Edad                      0
Semestre                  0
Carrera                   0
Modalidad                 0
Programación              0
Matemáticas               0
Ciencia de Datos          0
Asistencia (%)            0
Tareas entregadas         0
Horas estudio semanal     0
Horas sueño               0
Uso plataforma semanal    0
Trabajo en equipo         0
Dispositivo principal     0
dtype: int64

In [80]:
#Distribución por carrera
df_json["Carrera"].value_counts()

Carrera
Ciencia de Datos            5
Ingeniería en Software      4
Sistemas Computacionales    3
Name: count, dtype: int64

In [81]:
df_json["Modalidad"].value_counts()

Modalidad
Presencial    8
Híbrida       4
Name: count, dtype: int64

In [82]:
df_json["Dispositivo principal"].value_counts()

Dispositivo principal
Laptop         9
Computadora    2
Tablet         1
Name: count, dtype: int64

In [83]:
#Importar de PDF
##1. Instalar e importar librería
!pip install pdfplumber

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.13/dist-packages (0.11.10)
Requirement already satisfied: pdfminer.six==20260107 in /usr/local/lib/python3.13/dist-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in /usr/local/lib/python3.13/dist-packages (from pdfplumber) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in /usr/local/lib/python3.13/dist-packages (from pdfplumber) (5.14.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (3.4.9)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)

In [84]:
#Importar librería para abrir y leer archivos PDF
import pdfplumber
import pandas as pd
#Modulo re, permite trabajar con expresiones regulares
#para buscar patrones dentro de texto

In [85]:
#Crear una cadena de texto vacía
texto = " "

#Abrir el PDF e iterar por sus páginas para extraer el texto:
with pdfplumber.open("/content/datos_estudiantes.pdf") as pdf:
  for pagina in pdf.pages:
    texto += pagina.extract_text() + "\n"
    print(texto)

 Datos académicos de estudiantes — Ejemplo para extracción y análisis
Este documento contiene datos ficticios generados únicamente con fines educativos. Las
tablas incluyen información académica y de hábitos de estudio de un grupo de
estudiantes.
Demográfico
ID Nombre Edad Semestre Carrera Modalidad
101 Ana López 19 2 Ingeniería en Software Presencial
102 Carlos Rivera 21 4 Ciencia de Datos Presencial
103 Sofía Martínez 20 3 Ingeniería en Software Híbrida
104 Daniel Torres 22 6 Sistemas Computacionales Presencial
105 Mariana García 19 2 Ciencia de Datos Híbrida
106 Luis Hernández 23 7 Sistemas Computacionales Presencial
107 Valeria Sánchez 20 4 Ciencia de Datos Presencial
108 Jorge Ramírez 21 5 Ingeniería en Software Híbrida
109 Fernanda Ortiz 18 1 Ciencia de Datos Presencial
110 Miguel Flores 22 6 Sistemas Computacionales Híbrida
111 Daniela Cruz 20 3 Ingeniería en Software Presencial
112 Ricardo Vega 24 8 Ciencia de Datos Presencial
Califiaciones
ID Programación Matemáticas Ciencia de Asistencia Tareas
Datos (%) entregadas
101 88 82 91 95 10
102 76 85 89 87 9

 Datos académicos de estudiantes — Ejemplo para extracción y análisis
Este documento contiene datos ficticios generados únicamente con fines educativos. Las
tablas incluyen información académica y de hábitos de estudio de un grupo de
estudiantes.
Demográfico
ID Nombre Edad Semestre Carrera Modalidad
101 Ana López 19 2 Ingeniería en Software Presencial
102 Carlos Rivera 21 4 Ciencia de Datos Presencial
103 Sofía Martínez 20 3 Ingeniería en Software Híbrida
104 Daniel Torres 22 6 Sistemas Computacionales Presencial
105 Mariana García 19 2 Ciencia de Datos Híbrida
106 Luis Hernández 23 7 Sistemas Computacionales Presencial
107 Valeria Sánchez 20 4 Ciencia de Datos Presencial
108 Jorge Ramírez 21 5 Ingeniería en Software Híbrida
109 Fernanda Ortiz 18 1 Ciencia de Datos Presencial
110 Miguel Flores 22 6 Sistemas Computacionales Híbrida
111 Daniela Cruz 20 3 Ingeniería en Software Presencial
112 Ricardo Vega 24 8 Ciencia de Datos Presencial
Califiaciones
ID Programación Matemáticas Ciencia de Asistencia Tareas
Datos (%) entregadas
101 88 82 91 95 10
102 76 85 89 87 9
103 94 90 93 98 10
104 68 74 72 80 8
105 91 88 95 96 10
106 72 69 75 78 7
107 86 92 90 93 10
108 79 81 77 85 8
109 95 94 96 100 10
110 65 73 70 76 7
111 84 79 87 91 9
112 90 86 92 94 10
Hábitos del estudiante
ID Horas estudio Horas Uso plataforma Trabajo en Dispositivo
semanal sueño semanal equipo principal
101 8 7.5 6 Sí Laptop
102 6 6.5 5 Sí Laptop
103 12 8.0 8 Sí Laptop
104 4 6.0 3 No Computadora
105 10 7.5 7 Sí Laptop
106 5 6.0 4 No Laptop
107 9 7.0 7 Sí Tablet
108 7 6.5 5 Sí Laptop
109 14 8.0 9 Sí Laptop
110 3 5.5 3 No Computadora

 Datos académicos de estudiantes — Ejemplo para extracción y análisis
Este documento contiene datos ficticios generados únicamente con fines educativos. Las
tablas incluyen información académica y de hábitos de estudio de un grupo de
estudiantes.
Demográfico
ID Nombre Edad Semestre Carrera Modalidad
101 Ana López 19 2 Ingeniería en Software Presencial
102 Carlos Rivera 21 4 Ciencia de Datos Presencial
103 Sofía Martínez 20 3 Ingeniería en Software Híbrida
104 Daniel Torres 22 6 Sistemas Computacionales Presencial
105 Mariana García 19 2 Ciencia de Datos Híbrida
106 Luis Hernández 23 7 Sistemas Computacionales Presencial
107 Valeria Sánchez 20 4 Ciencia de Datos Presencial
108 Jorge Ramírez 21 5 Ingeniería en Software Híbrida
109 Fernanda Ortiz 18 1 Ciencia de Datos Presencial
110 Miguel Flores 22 6 Sistemas Computacionales Híbrida
111 Daniela Cruz 20 3 Ingeniería en Software Presencial
112 Ricardo Vega 24 8 Ciencia de Datos Presencial
Califiaciones
ID Programación Matemáticas Ciencia de Asistencia Tareas
Datos (%) entregadas
101 88 82 91 95 10
102 76 85 89 87 9
103 94 90 93 98 10
104 68 74 72 80 8
105 91 88 95 96 10
106 72 69 75 78 7
107 86 92 90 93 10
108 79 81 77 85 8
109 95 94 96 100 10
110 65 73 70 76 7
111 84 79 87 91 9
112 90 86 92 94 10
Hábitos del estudiante
ID Horas estudio Horas Uso plataforma Trabajo en Dispositivo
semanal sueño semanal equipo principal
101 8 7.5 6 Sí Laptop
102 6 6.5 5 Sí Laptop
103 12 8.0 8 Sí Laptop
104 4 6.0 3 No Computadora
105 10 7.5 7 Sí Laptop
106 5 6.0 4 No Laptop
107 9 7.0 7 Sí Tablet
108 7 6.5 5 Sí Laptop
109 14 8.0 9 Sí Laptop
110 3 5.5 3 No Computadora
111 8 7.0 6 Sí Laptop
112 11 7.5 8 Sí Laptop

In [86]:
import re

patron_demografico = re.compile(
    #^ indica que la búsqueda debe de comenzar al inicio de una línea
    #(\d{3}) busca exactamente 3 dígitos: corresponde al ID
    #\s+ representa uno o más espacios
    #(.+?) captura el nombre del estudiante
    #(\d+) captura la edad
    #(\d+) captura el semestre
  r"^(\d{3})\s+(.+?)\s+(\d+)\s+(\d+)"

#Busca una de las tres carreras posibles
  r"(Ingeniería en Software|Ciencia de Datos|Sistemas Computacionales)"

  #Busca una de las dos modalidades posibles
  r"(Presencial|Híbrida)$",

  re.MULTILINE
)

In [87]:
#Busca dentro de "texto" todas las líneas que cumplen con el patrón que acabamos de definir
datos_demograficos = patron_demografico.findall(texto)

datos_demograficos

[]

In [88]:
#Convertir los datos demograficos en un DataFra,e de pandas
df_demograficos = pd.DataFrame(
    datos_demograficos,
    columns=["ID", "Nombre", "Edad", "Semestre", "Carrera", "Modalidad"]
)
df_demograficos.head()

Empty DataFrame
Columns: [ID, Nombre, Edad, Semestre, Carrera, Modalidad]
Index: []

#Tarea
##Extraer las dos columnas restantes:
Calificaciones y Hábitos

In [90]:
df_demograficos = pd.DataFrame(
    datos_demograficos,
    columns=["Calificaciones", "Hábitos"]
)
df_demograficos.head()

AttributeError: 'DataFrame' object has no attribute 'content'